#!/bin/sh
# Build the capture corpus from scratch, in a sandbox that contains nobody.
#
#   tools/mkcaptures.sh              writes captures/
#
# WHY GENERATED RATHER THAN RECORDED. The corpus used to be recordings of real
# sessions on the author's machines, and that turned out to carry a great deal
# more than terminal escape sequences: systemd machine-ids, a home directory
# listing, an employer's name, a process table, an MOTD. None of it was
# relevant to what the captures are FOR, which is exercising the VT parser and
# the renderer.
#
# You cannot filter that reliably. You cannot enumerate in advance everything a
# live desktop prints into a recording. So the corpus is generated instead,
# inside `env -i` with a synthetic HOME and a fixed prompt, and it is
# reproducible: run this and get the same bytes.
#
# Byte-for-byte reproducibility is also why FEAT is SCRIPTED rather than
# captured. It emits the sequences we want to test - attributes, colours,
# scroll regions, wrapping at the right margin - instead of hoping some real
# program happened to use them.
set -eu
here=$(cd "$(dirname "$0")/.." && pwd)
out=$here/captures
cap=$here/tools/ptycap.py
mkdir -p "$out"

box=$(mktemp -d)
trap 'rm -rf "$box"' EXIT
mkdir -p "$box/home/user/project" "$box/home/user/notes"
: > "$box/home/user/project/readme.txt"
: > "$box/home/user/project/main.c"
: > "$box/home/user/notes/todo.md"
printf 'hello\n' > "$box/home/user/hello.txt"

run() {                      # run <name> <seconds> <command...>
    name=$1; secs=$2; shift 2
    env -i HOME="$box/home/user" PATH=/usr/bin:/bin TERM=xterm-256color \
           PS1='$ ' LANG=C.UTF-8 \
        python3 "$cap" "$out/$name" 64 80 "$secs" "$@" >/dev/null 2>&1 || true
    printf '  %-10s %s bytes\n' "$name" "$(wc -c < "$out/$name" 2>/dev/null || echo 0)"
}

echo "mkcaptures: generating into $out"
# -n, NUMERIC IDS. Plain -la prints the OWNER, which is whoever ran this,
# and the first generated corpus therefore leaked the very username the
# recorded one had. env -i does not change who owns a file.
run LS    3 /bin/ls -lan "$box/home/user"
run TREE  3 /bin/ls -lanR "$box/home/user"
run SHELL 4 /bin/sh -c 'cd $HOME; ls; ls -lan project; echo done; printf "a\tb\tc\n"; head -5 hello.txt; false || echo status=$?'

# FEAT: the VT102 features the parser has to get right, emitted deliberately.
env -i PATH=/usr/bin:/bin TERM=xterm-256color python3 - "$out/FEAT" <<'PY'
import sys
E = "\x1b"
p = []
p.append(E + "[2J" + E + "[H")
p.append("PiTerm capture: attributes and colour\r\n")
for n, name in ((1, "bold"), (4, "underline"), (7, "reverse"), (9, "strike")):
    p.append(f"{E}[{n}m{name}{E}[0m ")
p.append("\r\n")
for c in range(8):
    p.append(f"{E}[3{c}m##{E}[4{c}m##{E}[0m")
p.append("\r\n")
for c in (16, 82, 118, 154, 190, 226, 202, 196):        # xterm-256 indices
    p.append(f"{E}[38;5;{c}m##{E}[48;5;{c}m##{E}[0m")
p.append("\r\n")
p.append(E + "[4;20r")                                   # scroll region
p.append(E + "[10;1H" + "scroll region rows 4 to 20\r\n")
for i in range(6):
    p.append(f"line {i}\r\n")
p.append(E + "[r")                                       # release it
p.append(E + "[24;1H" + "x" * 79 + "wrap\r\n")            # right margin wrap
p.append(E + "[H" + E + "[7X")                            # erase 7 chars
p.append(E + "[32;1H" + "done\r\n")
open(sys.argv[1], "w", encoding="utf-8", newline="").write("".join(p))
PY
printf '  %-10s %s bytes\n' FEAT "$(wc -c < "$out/FEAT")"

cat > "$out/README.md" <<'MD'
# captures/

Byte streams for replaying through the VT parser and the renderer.
`tools/vtcheck.sh` replays each one under the emulator and diffs the engine's
cell model against `pyte`, cell by cell, character and attributes.

**Every file here is generated by `tools/mkcaptures.sh`, not recorded.** The
corpus that these replaced was captured from live sessions, and carried far
more than escape sequences - machine identifiers, directory listings, process
tables. None of that was what the captures were for, and none of it can be
filtered out reliably, because you cannot know in advance what a real desktop
will print. Generating them makes the corpus reproducible as well as clean.

`FEAT` is scripted rather than captured for the same reason plus one more: it
emits exactly the features the parser must handle, instead of hoping a real
program used them.

The `.grid` files are the engine's own cell dumps and are regenerated by
`tools/vtcheck.sh`; they are not kept here.
MD
echo "mkcaptures: done"
